----------------------------------------------------
-- Create Table DBETL.ANAG_CLI
----------------------------------------------------
CREATE TABLE DBETL.ANAG_CLI
(
 ANAG_ID        NUMBER(38,0)
,ANAG_COGNOME   VARCHAR2(20) NOT NULL
,ANAG_NOME      VARCHAR2(20) NOT NULL
,ANAG_COD_FISC  CHAR(16) NOT NULL
,ANAG_CITTA     VARCHAR2(20) NOT NULL
,ANAG_STIP      NUMBER(9,2)
)
TABLESPACE TS_CORSO
STORAGE (INITIAL 250K);

COMMIT; 

INSERT INTO DBETL.ANAG_CLI VALUES ( 1,'GERENZANO','Giuliano','GRNGLN84H14F205S','Napoli', 800);
INSERT INTO DBETL.ANAG_CLI VALUES ( 2,'DURANTE','Roberto','DRNRRT70D23C422J','Palermo', 1200);
INSERT INTO DBETL.ANAG_CLI VALUES ( 3,'CASTELLETTO','Giacomo','CSTGCM65D12C422H','Cosenza', 900);
INSERT INTO DBETL.ANAG_CLI VALUES ( 4,'AMADEI','Antonio','MDANTN77D27C529D','Verona', 1000);
INSERT INTO DBETL.ANAG_CLI VALUES ( 5,'ROCCATI','Cosimo','RCCCSM82D02F839S','Milano', 900);
INSERT INTO DBETL.ANAG_CLI VALUES ( 6,'PALLADINO','Alberto','PLLLRT73D23A108E','Roma', 1200);
INSERT INTO DBETL.ANAG_CLI VALUES ( 7,'ZIMMITI','Lorenzo','ZMMLNZ70A11F641K','Firenze', 1400);
INSERT INTO DBETL.ANAG_CLI VALUES ( 8,'PASCOLI','Miriam','PSCMRM99H52B234D','Torino', 2000);
INSERT INTO DBETL.ANAG_CLI VALUES ( 9,'PALLOTTA','Veronica','PLLVNC81C71D762U','Venezia', 1800);
INSERT INTO DBETL.ANAG_CLI VALUES (10,'MORABITO','Gianmarco','MRBGMR84B28A570L','Napoli', 1700);

COMMIT;