----------------------------------------------------
-- Create Table DBETL.MARKET_FORNITORI
----------------------------------------------------
CREATE TABLE DBETL.MARKET_FORNITORI
(
 ID_FORNITORE    INTEGER PRIMARY KEY NOT NULL
,DENOMINAZIONE   CHAR(30) NOT NULL
,SEDE_CENTRALE   CHAR(30) NOT NULL
)
TABLESPACE TS_CORSO
STORAGE (INITIAL 250K);

COMMIT; 

INSERT INTO DBETL.MARKET_FORNITORI VALUES (1,'Barilla','Lazio');
INSERT INTO DBETL.MARKET_FORNITORI VALUES (2,'Amadori','Campania');
INSERT INTO DBETL.MARKET_FORNITORI VALUES (3,'Feffero','Lombardia');
INSERT INTO DBETL.MARKET_FORNITORI VALUES (4,'Kraft','Campania');
INSERT INTO DBETL.MARKET_FORNITORI VALUES (5,'Cirio','Lazio');
INSERT INTO DBETL.MARKET_FORNITORI VALUES (6,'Lenor','Sicilia');
INSERT INTO DBETL.MARKET_FORNITORI VALUES (7,'Granarolo','Campania');
INSERT INTO DBETL.MARKET_FORNITORI VALUES (8,'Garofalo','Lombardia');
INSERT INTO DBETL.MARKET_FORNITORI VALUES (9,'Zuegg','Lazio');
INSERT INTO DBETL.MARKET_FORNITORI VALUES (10,'Mellin','Calabria');
INSERT INTO DBETL.MARKET_FORNITORI VALUES (11,'Nestle','Puglia');
INSERT INTO DBETL.MARKET_FORNITORI VALUES (12,'Rana','Lazio');

COMMIT;