
----------------------------------------------------
-- Create Table DBETL.ANAGRAFE_DIPENDENTI
----------------------------------------------------
CREATE TABLE DBETL.ANAGRAFE_DIPENDENTI
(
 ID_ANAG         INTEGER PRIMARY KEY NOT NULL
,COGNOME         CHAR(30) NOT NULL
,NOME            CHAR(30) NOT NULL
,DT_NASC         DATE
,CITTA           CHAR(40) NOT NULL
,SESSO           CHAR(1)
)
TABLESPACE TS_CORSO
STORAGE (INITIAL 250K);

COMMIT; 
-- alter session set NLS_DATE_FORMAT='DD-MM-YYYY';
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES ( 1,'Calenzano','Giuliano','04-10-1967','Milano','U');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES ( 2,'De Amicis','Roberto','01-01-1978','Roma','U');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES ( 3,'Venanzoni','Giacomo','16-12-1982','Milano','U');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES ( 4,'Rigo','Antonio','15-02-1971','Napoli','U');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES ( 7,'Benadusi','Cosimo','26-04-1955','Roma','U');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES ( 9,'Colzani','Alberto','11-07-1963','Torino','U');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES (11,'Barba','Lorenzo','09-08-1974','Firenze','U');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES (12,'Proietti','Miriam','04-01-1990','Catania','D');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES (15,'Zimmerman','Veronica','30-11-1968','Roma','D');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES (19,'Di Vincenzo','Gianmarco','29-10-1979','Palermo','U');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES (21,'Grassi','Emma','26-05-1982','Bologna','D');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES (25,'Polito','Cecilia','03-02-1985','Pescara','D');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES (27,'Mosca','Andrea','12-12-1991','Napoli','U');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES (29,'Rettore','Francesca','04-09-1970','Milano','D');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES (31,'Morabito','Dario','13-01-1988','Torino','U');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES (33,'Oppini','Massimiliano','25-09-1973','Genova','U');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES (38,'Zottola','Carla','30-04-1965','Lecce','D');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES (39,'Minelli','Alberto','23-06-1991','Firenze','U');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES (41,'De Maio','Luigi','17-08-1985','Siena','U');
INSERT INTO DBETL.ANAGRAFE_DIPENDENTI VALUES (45,'Alterisi','Anna','01-02-1974','Milano','D');

COMMIT; 