----------------------------------------------------
-- Create Table STIPENDI_DIPEN
----------------------------------------------------
CREATE TABLE DBETL.STIPENDI_DIPEN
(
 ID_ANAG            INTEGER PRIMARY KEY NOT NULL
,STIPENDIO          NUMBER(8,2) NOT NULL
)
TABLESPACE TS_CORSO
STORAGE (INITIAL 250K);

COMMIT;

INSERT INTO DBETL.STIPENDI_DIPEN VALUES (1, 1700);
INSERT INTO DBETL.STIPENDI_DIPEN VALUES (2, 1900);
INSERT INTO DBETL.STIPENDI_DIPEN VALUES (3, 2100);
INSERT INTO DBETL.STIPENDI_DIPEN VALUES (4, 2250);
INSERT INTO DBETL.STIPENDI_DIPEN VALUES (6, 3000);
INSERT INTO DBETL.STIPENDI_DIPEN VALUES (7, 1750);
INSERT INTO DBETL.STIPENDI_DIPEN VALUES (8, 1540);
INSERT INTO DBETL.STIPENDI_DIPEN VALUES (10, 1300);
INSERT INTO DBETL.STIPENDI_DIPEN VALUES (11, 2150);
INSERT INTO DBETL.STIPENDI_DIPEN VALUES (12, 4900);
INSERT INTO DBETL.STIPENDI_DIPEN VALUES (13, 3260);
INSERT INTO DBETL.STIPENDI_DIPEN VALUES (16, 2984);
INSERT INTO DBETL.STIPENDI_DIPEN VALUES (18, 1983);
INSERT INTO DBETL.STIPENDI_DIPEN VALUES (19, 1487);
INSERT INTO DBETL.STIPENDI_DIPEN VALUES (20, 2982); 

COMMIT;