----------------------------------------------------
-- Create Table DBETL.TB_IMPIEGATI
----------------------------------------------------
CREATE TABLE DBETL.TB_IMPIEGATI
(
 ID_IMP    INTEGER PRIMARY KEY NOT NULL
,NOME      CHAR(50)
,LIVELLO   INTEGER
)
TABLESPACE TS_CORSO 
STORAGE (INITIAL 250K);

COMMIT; 

INSERT INTO DBETL.TB_IMPIEGATI VALUES(1, 'Albertosi', 3);
INSERT INTO DBETL.TB_IMPIEGATI VALUES(2, 'Delle Vecchie', 4);
INSERT INTO DBETL.TB_IMPIEGATI VALUES(3, 'Verdi', 2);
INSERT INTO DBETL.TB_IMPIEGATI VALUES(4, 'Carotenuto', 2);
INSERT INTO DBETL.TB_IMPIEGATI VALUES(5, 'Ziveri', 3);
INSERT INTO DBETL.TB_IMPIEGATI VALUES(6, 'Toscani', 2);
INSERT INTO DBETL.TB_IMPIEGATI VALUES(7, 'Rosati', 1);
INSERT INTO DBETL.TB_IMPIEGATI VALUES(8, 'Gambardella', 5);
INSERT INTO DBETL.TB_IMPIEGATI VALUES(9, 'Melicori', 4);
INSERT INTO DBETL.TB_IMPIEGATI VALUES(10, 'Pollastri', 1);
INSERT INTO DBETL.TB_IMPIEGATI VALUES(11, 'Palumbo', 3);
INSERT INTO DBETL.TB_IMPIEGATI VALUES(12, 'Napolitano', 5);
INSERT INTO DBETL.TB_IMPIEGATI VALUES(13, 'Minghi', 2);
INSERT INTO DBETL.TB_IMPIEGATI VALUES(14, 'Federati', 4);
INSERT INTO DBETL.TB_IMPIEGATI VALUES(15, 'Pulcioni', 1);
INSERT INTO DBETL.TB_IMPIEGATI VALUES(16, 'Padalino', 2);
INSERT INTO DBETL.TB_IMPIEGATI VALUES(17, 'De Felice', 3);
INSERT INTO DBETL.TB_IMPIEGATI VALUES(18, 'Costantini', 5);

COMMIT;
