
----------------------------------------------------
-- Create Table DBETL.RECITA
----------------------------------------------------
CREATE TABLE DBETL.RECITA
(
 ID_ATT        INT
,COD_FILM      INT
,CONSTRAINT PK_RECITA
 PRIMARY KEY (ID_ATT, COD_FILM)
)
TABLESPACE TS_CORSO
STORAGE (INITIAL 250K);

COMMIT;

INSERT INTO DBETL.RECITA VALUES (1,1);
INSERT INTO DBETL.RECITA VALUES (1,2);
INSERT INTO DBETL.RECITA VALUES (1,3);
INSERT INTO DBETL.RECITA VALUES (2,4);
INSERT INTO DBETL.RECITA VALUES (2,5);
INSERT INTO DBETL.RECITA VALUES (3,6);
INSERT INTO DBETL.RECITA VALUES (4,7);
INSERT INTO DBETL.RECITA VALUES (4,8);
INSERT INTO DBETL.RECITA VALUES (4,9);
INSERT INTO DBETL.RECITA VALUES (4,10);
INSERT INTO DBETL.RECITA VALUES (4,11);
INSERT INTO DBETL.RECITA VALUES (5,12);
INSERT INTO DBETL.RECITA VALUES (5,13);
INSERT INTO DBETL.RECITA VALUES (6,14);
INSERT INTO DBETL.RECITA VALUES (6,15);
INSERT INTO DBETL.RECITA VALUES (7,16);
INSERT INTO DBETL.RECITA VALUES (7,17);
INSERT INTO DBETL.RECITA VALUES (8,18);
INSERT INTO DBETL.RECITA VALUES (8,19);
INSERT INTO DBETL.RECITA VALUES (9,20);
INSERT INTO DBETL.RECITA VALUES (9,21);
INSERT INTO DBETL.RECITA VALUES (9,22);
INSERT INTO DBETL.RECITA VALUES (9,23);
INSERT INTO DBETL.RECITA VALUES (10,24);
INSERT INTO DBETL.RECITA VALUES (10,25);
INSERT INTO DBETL.RECITA VALUES (10,26);
INSERT INTO DBETL.RECITA VALUES (10,27);
INSERT INTO DBETL.RECITA VALUES (11,28);
INSERT INTO DBETL.RECITA VALUES (12,29);
INSERT INTO DBETL.RECITA VALUES (12,30);
INSERT INTO DBETL.RECITA VALUES (12,31);
INSERT INTO DBETL.RECITA VALUES (13,32);
INSERT INTO DBETL.RECITA VALUES (13,33);
INSERT INTO DBETL.RECITA VALUES (13,34);
INSERT INTO DBETL.RECITA VALUES (13,35);
INSERT INTO DBETL.RECITA VALUES (13,36);
INSERT INTO DBETL.RECITA VALUES (14,37);
INSERT INTO DBETL.RECITA VALUES (15,38);
INSERT INTO DBETL.RECITA VALUES (15,39);
INSERT INTO DBETL.RECITA VALUES (16,40);
INSERT INTO DBETL.RECITA VALUES (17,41);
INSERT INTO DBETL.RECITA VALUES (17,42);
INSERT INTO DBETL.RECITA VALUES (18,43); 
INSERT INTO DBETL.RECITA VALUES (18,44);  
INSERT INTO DBETL.RECITA VALUES (19,45);
INSERT INTO DBETL.RECITA VALUES (20,46);

COMMIT;