ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

----------------------------------------------------
-- Creazione sinonimi per utente SYSTEM
----------------------------------------------------
CREATE OR REPLACE SYNONYM "SYSTEM"."SOCIETA" FOR "DBETL"."SOCIETA";
CREATE OR REPLACE SYNONYM "SYSTEM"."FATTURE" FOR "DBETL"."FATTURE";
CREATE OR REPLACE SYNONYM "SYSTEM"."ANAGRAFE_DIPENDENTI" FOR "DBETL"."ANAGRAFE_DIPENDENTI";
CREATE OR REPLACE SYNONYM "SYSTEM"."STIPENDI_DIPEN" FOR "DBETL"."STIPENDI_DIPEN";
CREATE OR REPLACE SYNONYM "SYSTEM"."COMUNI" FOR "DBETL"."COMUNI";
CREATE OR REPLACE SYNONYM "SYSTEM"."UFFICI" FOR "DBETL"."UFFICI";
CREATE OR REPLACE SYNONYM "SYSTEM"."TASK_DIPENDENTI" FOR "DBETL"."TASK_DIPENDENTI";
CREATE OR REPLACE SYNONYM "SYSTEM"."DIPENDENTI" FOR "DBETL"."DIPENDENTI";
CREATE OR REPLACE SYNONYM "SYSTEM"."PROGETTI" FOR "DBETL"."PROGETTI";
CREATE OR REPLACE SYNONYM "SYSTEM"."TB_02_UTENTI" FOR "DBETL"."TB_02_UTENTI";
CREATE OR REPLACE SYNONYM "SYSTEM"."TB_IMPIEGATI" FOR "DBETL"."TB_IMPIEGATI";
CREATE OR REPLACE SYNONYM "SYSTEM"."TB_ORDINI" FOR "DBETL"."TB_ORDINI";
CREATE OR REPLACE SYNONYM "SYSTEM"."TB_02_LIBRI" FOR "DBETL"."TB_02_LIBRI";
CREATE OR REPLACE SYNONYM "SYSTEM"."TB_02_PRESTITO_LIBRO" FOR "DBETL"."TB_02_PRESTITO_LIBRO";
CREATE OR REPLACE SYNONYM "SYSTEM"."ATTORI" FOR "DBETL"."ATTORI";
CREATE OR REPLACE SYNONYM "SYSTEM"."RECITA" FOR "DBETL"."RECITA";
CREATE OR REPLACE SYNONYM "SYSTEM"."FILM" FOR "DBETL"."FILM";
CREATE OR REPLACE SYNONYM "SYSTEM"."PROIEZIONI" FOR "DBETL"."PROIEZIONI";
CREATE OR REPLACE SYNONYM "SYSTEM"."SALE" FOR "DBETL"."SALE";
CREATE OR REPLACE SYNONYM "SYSTEM"."AEROPORTI" FOR "DBETL"."AEROPORTI";
CREATE OR REPLACE SYNONYM "SYSTEM"."VOLI" FOR "DBETL"."VOLI";
CREATE OR REPLACE SYNONYM "SYSTEM"."AEREO" FOR "DBETL"."AEREO";
CREATE OR REPLACE SYNONYM "SYSTEM"."DIPE_AZIENDA" FOR "DBETL"."DIPE_AZIENDA";
CREATE OR REPLACE SYNONYM "SYSTEM"."UFFICIO" FOR "DBETL"."UFFICIO";
CREATE OR REPLACE SYNONYM "SYSTEM"."BONUS" FOR "DBETL"."BONUS";
CREATE OR REPLACE SYNONYM "SYSTEM"."MARKET_CLIENTI" FOR "DBETL"."MARKET_CLIENTI";
CREATE OR REPLACE SYNONYM "SYSTEM"."MARKET_FATTURE" FOR "DBETL"."MARKET_FATTURE";
CREATE OR REPLACE SYNONYM "SYSTEM"."MARKET_PRODOTTI" FOR "DBETL"."MARKET_PRODOTTI";
CREATE OR REPLACE SYNONYM "SYSTEM"."MARKET_FORNITORI" FOR "DBETL"."MARKET_FORNITORI";
CREATE OR REPLACE SYNONYM "SYSTEM"."HOTEL" FOR "DBETL"."HOTEL";
CREATE OR REPLACE SYNONYM "SYSTEM"."HOTEL_CLIENTI" FOR "DBETL"."HOTEL_CLIENTI";
CREATE OR REPLACE SYNONYM "SYSTEM"."HOTEL_PREN" FOR "DBETL"."HOTEL_PREN";
CREATE OR REPLACE SYNONYM "SYSTEM"."ANAG_CLI" FOR "DBETL"."ANAG_CLI";

COMMIT;