SELECT NOME,COGNOME, EXTRACT(YEAR FROM DT_NASCITA) ANNO FROM DIPENDENTI;
SELECT NOME,COGNOME, TO_CHAR(DT_NASCITA,'YYYY') ANNO FROM DIPENDENTI;

SELECT EXTRACT(YEAR FROM TO_DATE('31-01-2001','DD-MM-YYYY') ) FROM DUAL;

SELECT EXTRACT(MONTH FROM TO_DATE('31-01-2001','DD-MM-YYYY') ) FROM DUAL;
SELECT EXTRACT(DAY FROM TO_DATE('31-01-2001','DD-MM-YYYY') ) FROM DUAL;
SELECT EXTRACT(HOUR FROM TO_TIMESTAMP ('31-01-2001 14:30:21') ) FROM DUAL;
SELECT EXTRACT(MINUTE FROM TO_TIMESTAMP ('31-01-2001 14:30:21') ) FROM DUAL;
SELECT EXTRACT(SECOND FROM TO_TIMESTAMP ('31-01-2001 14.30.21') ) FROM DUAL;


SELECT SYSDATE FROM DUAL;



SELECT 
NOME,COGNOME, DT_NASCITA 
FROM 
DIPENDENTI 
WHERE 
EXTRACT(YEAR FROM TO_DATE(SYSDATE,'DD-MM-YYYY')) - EXTRACT(YEAR FROM TO_DATE(DT_NASCITA,'DD-MM-YYYY'))=40 ;


SELECT 
NOME,COGNOME, DT_NASCITA 
FROM 
DIPENDENTI 
WHERE 
EXTRACT(YEAR FROM TO_DATE(SYSDATE,'DD-MM-YYYY')) - EXTRACT(YEAR FROM TO_DATE(DT_NASCITA,'DD-MM-YYYY'))=40 
AND
DT_NASCITA<=TRUNC(SYSDATE)

;


SELECT 
NOME,COGNOME,DT_NASCITA
FROM 
dipendenti
WHERE 
TRUNC(MONTHS_BETWEEN(SYSDATE, dt_nascita)/12) = 40; 


SELECT MONTHS_BETWEEN(SYSDATE, '31-01-1984') FROM DUAL;

SELECT ROUND(MONTHS_BETWEEN(SYSDATE, '07-11-1974')/12,0) FROM DUAL;

SELECT 
NOME,COGNOME,DT_NASCITA
FROM 
dipendenti
WHERE 
DT_NASCITA BETWEEN TO_DATE('01-01-1980','DD-MM-YYYY') AND TO_DATE('31-12-1981','DD-MM-YYYY');


SELECT 
RUOLO, ROUND(AVG(STIPENDIO),2) MEDIA
FROM 
dipendenti 
GROUP BY RUOLO
ORDER BY MEDIA

SELECT
COUNT(*) QUANTI, SESSO
FROM
DIPENDENTI
GROUP BY SESSO;


SELECT
COUNT(*) QUANTI, NOME, SESSO
FROM
DIPENDENTI
GROUP BY SESSO, NOME
ORDER BY QUANTI DESC;

EXPLAIN PLAN FOR 
SELECT 
RUOLO, ROUND(AVG(STIPENDIO),2) MEDIA
FROM 
dipendenti 
WHERE SESSO='U' AND RUOLO LIKE '%MANAGER%'
GROUP BY RUOLO
HAVING ROUND(AVG(STIPENDIO),2)>=1750
ORDER BY MEDIA;


SELECT * 
FROM TABLE(DBMS_XPLAN.DISPLAY);